/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description 心跳：返回当前服务器时间。
         *
         *     Heartbeat: return the current server time.
         *
         *     Returns:
         *         {"ok": True, "time": ISO 时间戳}。{"ok": True, "time": ISO timestamp}.
         */
        get: operations["ping_api_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Endpoint
         * @description 返回前端启动所需的语音/模型配置快照（可用性 + 当前 profile + 语音参数）。
         *
         *     Return the voice/model config snapshot needed by the frontend on startup
         *     (availability + current profile + voice parameters).
         *
         *     Returns:
         *         配置字典。The config dict.
         */
        get: operations["config_endpoint_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Config
         * @description 持久化非敏感配置并热重载；server 绑定类 / MCP 变更返回 restart_required=true。
         *
         *     Persist non-sensitive config and hot-reload; returns restart_required=true when
         *     server-bound settings or the MCP config changed.
         */
        patch: operations["patch_config_api_config_patch"];
        trace?: never;
    };
    "/api/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tts Synthesize
         * @description 文本转语音：调后端配置的 OpenAI 兼容 TTS 端点，返回音频字节。
         *
         *     请求体：{"text": "...", "voice": "可选，缺省用配置里的 voice"}
         *
         *     Text-to-speech: call the backend-configured OpenAI-compatible TTS endpoint and
         *     return the audio bytes. Request body: {"text": "...", "voice": "optional,
         *     defaults to the voice from config"}
         */
        post: operations["tts_synthesize_api_tts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Transcribe
         * @description 语音转写：接收 base64 音频 → 返回识别文本。
         *
         *     ASR transcription: accept base64 audio and return the recognized text.
         *
         *     Args:
         *         request: FastAPI 请求，JSON 体含 audio_base64。The FastAPI request with
         *             audio_base64 in the JSON body.
         *
         *     Returns:
         *         {"ok": True, "text": ...}，或错误响应。{"ok": True, "text": ...}, or an error response.
         */
        post: operations["voice_transcribe_api_voice_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/utter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Utter
         * @description 编排入口：文本(语音转写后/文字输入) → SSE 事件流。
         *
         *     事件：task_state / content_delta / question / error / done。
         *     question 事件后需操作者回答：POST /api/voice/answer {session_id, text}。
         *     请求体可带 session_id：续接已有会话（加载其历史作为多轮种子）。
         *
         *     Orchestration entry: text (post-ASR or typed input) → SSE event stream. Events:
         *     task_state / content_delta / question / error / done. After a question event the
         *     operator must answer via POST /api/voice/answer {session_id, text}. The request
         *     body may carry session_id to resume an existing session (loading its history as
         *     the multi-turn seed).
         */
        post: operations["voice_utter_api_voice_utter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Answer
         * @description 投递操作者对澄清/确认问题的回答，解除 pipeline 的 ask() 阻塞。
         *
         *     Deliver the operator's answer to a clarification/confirmation question,
         *     unblocking the pipeline's ask().
         */
        post: operations["voice_answer_api_voice_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Task Stop
         * @description 停止该会话的整个任务（CancellationToken → executor/子进程中止）。
         *
         *     Stop the whole task of the session (CancellationToken → executor/subprocess abort).
         */
        post: operations["task_stop_api_task__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tools List
         * @description 工具清单：后端 @tool 注册中心的 OpenAI schema 数组（供控制台展示）。
         *
         *     Tool listing: OpenAI schemas from the backend @tool registry (for console display).
         */
        get: operations["tools_list_api_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tools Call
         * @description 执行单个工具：校验 name/args、非 read 工具需显式确认、返回执行输出。
         *
         *     Invoke a single tool: validate name/args, require explicit confirmation for
         *     non-read tools, and return the execution output.
         *
         *     Args:
         *         request: FastAPI 请求，JSON 体为 {name, args, confirm?}。The FastAPI request
         *             with a JSON body of {name, args, confirm?}.
         *
         *     Returns:
         *         执行结果 {ok, status, output}，或错误 JSONResponse。The execution result
         *         {ok, status, output}, or an error JSONResponse.
         */
        post: operations["tools_call_api_tools_call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Env
         * @description 读取当前环境快照（environment.md 的内容）。
         *
         *     Read the current environment snapshot (the content of environment.md).
         */
        get: operations["env_api_env_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memory List
         * @description 列出全部长期记忆事实（facts）。
         *
         *     List all long-term memory facts.
         */
        get: operations["memory_list_api_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Memory Delete
         * @description 按主题删除一条长期记忆。
         *
         *     Delete a long-term memory entry by topic.
         */
        delete: operations["memory_delete_api_memory__topic__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schedules List
         * @description 列出全部已注册的定时任务。
         *
         *     List all registered scheduled jobs.
         */
        get: operations["schedules_list_api_schedules_get"];
        put?: never;
        /**
         * Schedules Add
         * @description 注册一个定时任务：body {cron, prompt}，cron 与 prompt 必填。
         *
         *     Register a scheduled job: body {cron, prompt}; cron and prompt are required.
         */
        post: operations["schedules_add_api_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Schedules Delete
         * @description 按 ID 取消一个定时任务。
         *
         *     Cancel a scheduled job by its ID.
         */
        delete: operations["schedules_delete_api_schedules__sid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History List
         * @description 列出最近的会话历史（最多 limit 条）。
         *
         *     List recent conversation history (up to ``limit`` entries).
         */
        get: operations["history_list_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{conv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Get
         * @description 获取单个会话详情；不存在时返回 404。
         *
         *     Get the detail of a single conversation; returns 404 when it does not exist.
         */
        get: operations["history_get_api_history__conv_id__get"];
        put?: never;
        post?: never;
        /**
         * History Delete
         * @description 删除指定会话历史。
         *
         *     Delete the specified conversation history.
         */
        delete: operations["history_delete_api_history__conv_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Library List
         * @description 列出已存档的成功任务（按时间倒序）。
         *
         *     List archived successful tasks, newest first.
         */
        get: operations["library_list_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Library Detail
         * @description 取单条任务详情。
         *
         *     Fetch one archived task.
         */
        get: operations["library_detail_api_library__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Library Delete
         * @description 删除一条任务存档。
         *
         *     Delete one archived task.
         */
        delete: operations["library_delete_api_library__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sessions List
         * @description 会话列表；?archived=true 只归档 / false(默认) 排除归档。
         *
         *     List sessions; ?archived=true returns only archived ones, false (default) excludes archived.
         */
        get: operations["sessions_list_api_sessions_get"];
        put?: never;
        /**
         * Sessions Create
         * @description 新建会话（可选 body {"name"}；缺省名「新会话」），返回 {id, name, ...}。
         *
         *     Create a new session (optional body {"name"}; defaults to "新会话"), returns {id, name, ...}.
         */
        post: operations["sessions_create_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sessions Delete
         * @description 删除指定会话（含其全部消息）。
         *
         *     Delete the specified session (including all of its messages).
         */
        delete: operations["sessions_delete_api_sessions__sid__delete"];
        options?: never;
        head?: never;
        /**
         * Sessions Patch
         * @description 更新会话：body {name} 重命名 或 {archived: bool} 归档/取消归档（可同时）。
         *
         *     Update a session: body {name} renames or {archived: bool} archives/unarchives (both allowed at once).
         */
        patch: operations["sessions_patch_api_sessions__sid__patch"];
        trace?: never;
    };
    "/api/sessions/{sid}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sessions Clear
         * @description 清除上下文：清空该会话消息（会话记录与 name 保留）。
         *
         *     Clear the context: wipe the session's messages (the session record and its name are kept).
         */
        post: operations["sessions_clear_api_sessions__sid__clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Full
         * @description 设置页可编辑快照（密钥不回显）。
         *
         *     Editable snapshot for the settings page (secrets are not echoed back).
         */
        get: operations["config_full_api_config_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Secrets
         * @description 设置/清除密钥（value 为空字符串=清除）。path 形如 llm.api_key / llm.profiles.deepseek / server.api_token。
         *
         *     只写 config.secrets.yaml，永不把密钥值放进响应。
         *
         *     Set/clear a secret (empty value string = clear). path looks like llm.api_key /
         *     llm.profiles.deepseek / server.api_token. Only writes config.secrets.yaml and never
         *     puts secret values into the response.
         */
        put: operations["put_secrets_api_config_secrets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detection
         * @description 聚合检测：环境快照 + 配置健康 + 三项连通性（设置页「检测全部」按钮）。
         *
         *     Aggregated detection: environment snapshot + config health + three connectivity
         *     checks (the "check all" button on the settings page).
         */
        get: operations["detection_api_detection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description 返回合并后的厂商目录，按 kind（llm/asr/tts）分组，不含密钥。
         *
         *     Return the merged vendor catalog grouped by kind (llm/asr/tts), without secrets.
         */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/fetch-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Models
         * @description 拉取某 profile 的可用模型列表（按协议分派：openai / anthropic / gemini）。
         *
         *     请求体：{"section": "llm|asr|tts", "profile": {完整 profile dict，含 name/endpoint/chat_path/api_key_env}}
         *     profile 传完整 dict，未保存的新 profile 也能测（密钥由服务端按优先级解析，不回显）。
         *
         *     Fetch the available model list for a profile (dispatched by protocol: openai / anthropic / gemini).
         *
         *     Request body: {"section": "llm|asr|tts", "profile": {full profile dict incl. name/endpoint/chat_path/api_key_env}}
         *     The full profile dict is passed in, so an unsaved new profile can also be tested
         *     (the key is resolved server-side by priority and never echoed).
         */
        post: operations["fetch_models_api_providers_fetch_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spa Handler
         * @description SPA 兜底路由：托管静态文件，未知 /api 路径返回 404，非 api 导航回退 index.html。
         *
         *     SPA fallback route: serve static files, return 404 for unknown /api paths, and fall back to index.html for non-API navigation.
         */
        get: operations["spa_handler__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AckResponse
         * @description 操作确认响应。
         *
         *     Operation acknowledgement response.
         */
        AckResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Ack
             * @default
             */
            ack: string;
        };
        /**
         * AgentConfigOut
         * @description Agent 配置输出（递归限制、多代理、故障转移模型列表）。
         *
         *     Agent config output (recursion limit, multi-agent, failover model list).
         */
        AgentConfigOut: {
            /**
             * Recursion Limit
             * @default 12
             */
            recursion_limit: number;
            /**
             * Multi Agent
             * @default false
             */
            multi_agent: boolean;
            /**
             * Models Failover
             * @default []
             */
            models_failover: string[];
        };
        /**
         * ApiResponse
         * @description 所有 API 响应的基类，含通用 ok/error 字段。
         *
         *     Base class for all API responses, with common ``ok`` / ``error`` fields.
         */
        ApiResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /**
         * CatalogResponse
         * @description 厂商目录端点响应。
         *
         *     ``/api/providers/catalog`` response.
         */
        CatalogResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Catalog
             * @default {}
             */
            catalog: {
                [key: string]: components["schemas"]["ProviderPreset"][];
            };
        };
        /**
         * ConfigFullResponse
         * @description 完整配置端点响应。
         *
         *     ``/api/config`` full response.
         */
        ConfigFullResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            editable: components["schemas"]["EditableSnapshot"];
        };
        /**
         * ConfigHealthOut
         * @description 配置健康状态输出。
         *
         *     Configuration health status output.
         */
        ConfigHealthOut: {
            /** Ok */
            ok: boolean;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["DetectionIssue"][];
        };
        /**
         * ConfigResponse
         * @description 配置状态端点响应（LLM/ASR/TTS 可用性、唤醒词、VAD）。
         *
         *     ``/api/config`` status response (LLM/ASR/TTS availability, wake word, VAD).
         */
        ConfigResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Llm Available
             * @default false
             */
            llm_available: boolean;
            /**
             * Llm Profile
             * @default
             */
            llm_profile: string;
            /**
             * Asr Available
             * @default false
             */
            asr_available: boolean;
            /**
             * Asr Profile
             * @default
             */
            asr_profile: string;
            /**
             * Tts Available
             * @default false
             */
            tts_available: boolean;
            /**
             * Tts Profile
             * @default
             */
            tts_profile: string;
            /** Tts Voice */
            tts_voice?: string | null;
            /** Tts Model */
            tts_model?: string | null;
            wake_word: components["schemas"]["WakeWordConfig"];
            vad: components["schemas"]["VadConfig"];
        };
        /**
         * ConnectivityResult
         * @description 单条连通性检查结果。
         *
         *     A single connectivity check result.
         */
        ConnectivityResult: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * DetectionIssue
         * @description 单条检测问题（级别 + 键 + 描述）。
         *
         *     A single detection issue (level + key + message).
         */
        DetectionIssue: {
            /** Level */
            level: string;
            /** Key */
            key: string;
            /** Message */
            message: string;
        };
        /**
         * DetectionReportOut
         * @description 环境检测报告（系统信息 + 配置健康 + 连通性检查）。
         *
         *     Environment detection report (system info + config health + connectivity checks).
         */
        DetectionReportOut: {
            /**
             * Environment
             * @default {}
             */
            environment: {
                [key: string]: unknown;
            };
            config: components["schemas"]["ConfigHealthOut"];
            /**
             * Connectivity
             * @default []
             */
            connectivity: components["schemas"]["ConnectivityResult"][];
        };
        /**
         * DetectionResponse
         * @description 环境检测端点响应。
         *
         *     ``/api/detection`` response.
         */
        DetectionResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            report: components["schemas"]["DetectionReportOut"];
        };
        /**
         * EditableSnapshot
         * @description 配置编辑快照（前端 settings 页面的数据源）。
         *
         *     Configuration editable snapshot (data source for the front-end settings page).
         */
        EditableSnapshot: {
            llm: components["schemas"]["SectionEditable"];
            asr: components["schemas"]["SectionEditable"];
            tts: components["schemas"]["TtsSectionEditable"];
            wake_word: components["schemas"]["WakeWordConfig"];
            vad: components["schemas"]["VadConfig"];
            agent: components["schemas"]["AgentConfigOut"];
            llm_client: components["schemas"]["LlmClientConfigOut"];
            tools: components["schemas"]["ToolsConfigOut"];
            permissions: components["schemas"]["PermissionsOut"];
            mcp: components["schemas"]["McpConfigOut"];
            rag: components["schemas"]["RagConfigOut"];
            server: components["schemas"]["ServerConfigOut"];
        };
        /**
         * EnvResponse
         * @description 环境信息端点响应（environment.md 内容）。
         *
         *     ``/api/env`` response (content of ``environment.md``).
         */
        EnvResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Content
             * @default
             */
            content: string;
        };
        /**
         * FactItem
         * @description 单条长期记忆事实。
         *
         *     A single long-term memory fact entry.
         */
        FactItem: {
            /** Topic */
            topic: string;
            /** Content */
            content: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Ts
             * @default
             */
            ts: string;
        };
        /**
         * FetchModelsResponse
         * @description 获取模型列表端点响应。
         *
         *     ``/api/providers/models`` fetch response.
         */
        FetchModelsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * FunctionParams
         * @description 工具函数参数的 JSON Schema 描述。
         *
         *     JSON Schema description of tool function parameters.
         */
        FunctionParams: {
            /**
             * Type
             * @default object
             */
            type: string;
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: unknown;
            };
            /**
             * Required
             * @default []
             */
            required: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryConversation
         * @description 历史会话摘要（列表视图）。
         *
         *     Conversation summary (list view).
         */
        HistoryConversation: {
            /** Id */
            id: string;
            /** Created */
            created: string;
            /** Updated */
            updated: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Message Count */
            message_count: number;
        };
        /**
         * HistoryConversationDetail
         * @description 会话详情：详情响应不含 message_count（仅列表接口统计）。
         *
         *     Conversation detail: excludes ``message_count`` (only counted in the list
         *     endpoint).
         */
        HistoryConversationDetail: {
            /** Id */
            id: string;
            /** Created */
            created: string;
            /** Updated */
            updated: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["HistoryMessage"][];
        };
        /**
         * HistoryDetailResponse
         * @description 历史会话详情端点响应。
         *
         *     ``/api/history/<id>`` detail response.
         */
        HistoryDetailResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            conversation?: components["schemas"]["HistoryConversationDetail"] | null;
        };
        /**
         * HistoryListResponse
         * @description 历史会话列表端点响应。
         *
         *     ``/api/history`` conversation list response.
         */
        HistoryListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Conversations
             * @default []
             */
            conversations: components["schemas"]["HistoryConversation"][];
        };
        /**
         * HistoryMessage
         * @description 历史记录中的单条消息。
         *
         *     A single message in a conversation history.
         */
        HistoryMessage: {
            /** Role */
            role: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * LibraryDetailResponse
         * @description 任务库详情响应。
         *
         *     The task-library detail response.
         */
        LibraryDetailResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            task: components["schemas"]["TaskLibraryItem"];
        };
        /**
         * LibraryListResponse
         * @description 任务库列表响应。
         *
         *     The task-library list response.
         */
        LibraryListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskLibraryItem"][];
        };
        /**
         * LlmClientConfigOut
         * @description LLM 客户端配置输出（重试、熔断、超时参数）。
         *
         *     LLM client config output (retry, circuit breaker, timeout parameters).
         */
        LlmClientConfigOut: {
            /**
             * Retry Max
             * @default 3
             */
            retry_max: number;
            /**
             * Retry Backoff Base
             * @default 0.5
             */
            retry_backoff_base: number;
            /**
             * Retry Backoff Max
             * @default 10
             */
            retry_backoff_max: number;
            /**
             * Circuit Breaker Threshold
             * @default 5
             */
            circuit_breaker_threshold: number;
            /**
             * Circuit Breaker Cooldown
             * @default 30
             */
            circuit_breaker_cooldown: number;
            /**
             * Request Timeout
             * @default 60
             */
            request_timeout: number;
        };
        /**
         * McpConfigOut
         * @description MCP 配置输出。
         *
         *     MCP config output.
         */
        McpConfigOut: {
            /**
             * Servers
             * @default []
             */
            servers: components["schemas"]["McpServerOut"][];
        };
        /**
         * McpServerOut
         * @description 单个 MCP 服务器配置。
         *
         *     A single MCP server configuration.
         */
        McpServerOut: {
            /** Name */
            name: string;
            /** Command */
            command: string;
            /**
             * Args
             * @default []
             */
            args: string[];
        };
        /**
         * MemoryListResponse
         * @description 记忆列表端点响应。
         *
         *     ``/api/memory`` list response.
         */
        MemoryListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["FactItem"][];
        };
        /**
         * PatchConfigResponse
         * @description 配置补丁端点响应。
         *
         *     ``PATCH /api/config`` response.
         */
        PatchConfigResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Restart Required
             * @default false
             */
            restart_required: boolean;
        };
        /**
         * PermissionRuleOut
         * @description 权限规则（前端展示与编辑用）。A permission rule (for front-end display and editing).
         */
        PermissionRuleOut: {
            /** Match */
            match: string;
            /** Action */
            action: string;
        };
        /**
         * PermissionTiersOut
         * @description 各风险层级的默认动作。The default action per risk tier.
         */
        PermissionTiersOut: {
            /** Read */
            read: string;
            /** Write */
            write: string;
            /** Exec */
            exec: string;
        };
        /**
         * PermissionsOut
         * @description 工具权限策略快照。Tool permission policy snapshot.
         */
        PermissionsOut: {
            /** Default Action */
            default_action: string;
            tiers: components["schemas"]["PermissionTiersOut"];
            /** Rules */
            rules: components["schemas"]["PermissionRuleOut"][];
        };
        /**
         * PingResponse
         * @description ping 端点响应，返回服务器时间戳。
         *
         *     ``/api/ping`` response carrying the server timestamp.
         */
        PingResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /** Time */
            time: string;
        };
        /**
         * ProfileEditable
         * @description editable_snapshot 的 profile（去 api_key）。extra=allow 保留用户透传键。
         *
         *     Profile within ``editable_snapshot`` (``api_key`` stripped). ``extra=allow``
         *     preserves user pass-through keys.
         */
        ProfileEditable: {
            /**
             * Provider
             * @default openai
             */
            provider: string;
            /**
             * Vendor
             * @default
             */
            vendor: string;
            /**
             * Endpoint
             * @default
             */
            endpoint: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Vision Model
             * @default
             */
            vision_model: string;
            /**
             * Chat Path
             * @default
             */
            chat_path: string;
            /**
             * Api Key Env
             * @default
             */
            api_key_env: string;
            /**
             * Timeout
             * @default 30
             */
            timeout: number;
            /**
             * Max Tokens
             * @default 4096
             */
            max_tokens: number;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Language
             * @default zh
             */
            language: string;
            /**
             * Voice
             * @default
             */
            voice: string;
            /**
             * Format
             * @default wav
             */
            format: string;
            /** Voice Ref */
            voice_ref?: string | null;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Models Path
             * @default
             */
            models_path: string;
            /**
             * Voices
             * @default []
             */
            voices: string[];
            /**
             * Compat
             * @default {}
             */
            compat: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * ProviderPreset
         * @description 厂商预设的完整结构（含所有可用字段）。
         *
         *     Full vendor preset structure (with all available fields).
         */
        ProviderPreset: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "llm" | "asr" | "tts";
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Provider
             * @default openai
             */
            provider: string;
            /**
             * Endpoint
             * @default
             */
            endpoint: string;
            /**
             * Chat Path
             * @default
             */
            chat_path: string;
            /** Models Path */
            models_path?: string | null;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Vision Models
             * @default []
             */
            vision_models: string[];
            /**
             * Voices
             * @default []
             */
            voices: string[];
            /**
             * Api Key Env
             * @default
             */
            api_key_env: string;
            /**
             * Compat
             * @default {}
             */
            compat: {
                [key: string]: unknown;
            };
            /**
             * Defaults
             * @default {}
             */
            defaults: {
                [key: string]: unknown;
            };
        };
        /**
         * PutSecretsResponse
         * @description 密钥写入端点响应。
         *
         *     ``PUT /api/secrets`` response.
         */
        PutSecretsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Set
             * @default false
             */
            set: boolean;
            /**
             * Path
             * @default
             */
            path: string;
        };
        /**
         * RagConfigOut
         * @description RAG 配置输出。
         *
         *     RAG config output.
         */
        RagConfigOut: {
            /**
             * Auto Index
             * @default true
             */
            auto_index: boolean;
        };
        /**
         * ScheduleAddResponse
         * @description 添加定时任务端点响应。
         *
         *     ``/api/schedules/add`` response.
         */
        ScheduleAddResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            schedule?: components["schemas"]["ScheduleItem"] | null;
        };
        /**
         * ScheduleItem
         * @description 单条定时任务。
         *
         *     A single scheduled task entry.
         */
        ScheduleItem: {
            /** Id */
            id: string;
            /** Cron */
            cron: string;
            /** Prompt */
            prompt: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * SchedulesResponse
         * @description 定时任务列表端点响应。
         *
         *     ``/api/schedules`` list response.
         */
        SchedulesResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Schedules
             * @default []
             */
            schedules: components["schemas"]["ScheduleItem"][];
        };
        /**
         * SectionEditable
         * @description 配置编辑区段（active profile + profiles 映射 + api_key_set 标记）。
         *
         *     Editable configuration section (active profile + profiles mapping +
         *     ``api_key_set`` flags).
         */
        SectionEditable: {
            /**
             * Active
             * @default
             */
            active: string;
            /**
             * Profiles
             * @default {}
             */
            profiles: {
                [key: string]: components["schemas"]["ProfileEditable"];
            };
            /**
             * Api Key Set
             * @default {}
             */
            api_key_set: {
                [key: string]: boolean;
            };
        };
        /**
         * ServerConfigOut
         * @description 服务器配置输出（主机、端口、浏览器启动、CORS、API token）。
         *
         *     Server config output (host, port, browser launch, CORS, API token).
         */
        ServerConfigOut: {
            /**
             * Host
             * @default 127.0.0.1
             */
            host: string;
            /**
             * Port
             * @default 8520
             */
            port: number;
            /**
             * Open Browser
             * @default true
             */
            open_browser: boolean;
            /**
             * Cors Origins
             * @default []
             */
            cors_origins: string[];
            /**
             * Api Token Set
             * @default false
             */
            api_token_set: boolean;
        };
        /**
         * SessionCreateResponse
         * @description 创建会话端点响应。
         *
         *     ``/api/sessions`` creation response.
         */
        SessionCreateResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            session: components["schemas"]["SessionOut"];
        };
        /**
         * SessionListResponse
         * @description 会话列表端点响应。
         *
         *     ``/api/sessions`` list response.
         */
        SessionListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Sessions
             * @default []
             */
            sessions: components["schemas"]["SessionOut"][];
        };
        /**
         * SessionOut
         * @description 会话输出模型。
         *
         *     Session output model.
         */
        SessionOut: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Created
             * @default
             */
            created: string;
            /**
             * Updated
             * @default
             */
            updated: string;
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
        };
        /**
         * TaskLibraryItem
         * @description 任务库条目（一次成功任务的存档）。
         *
         *     One archived successful task.
         */
        TaskLibraryItem: {
            /** Id */
            id: number;
            /** Goal */
            goal: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Steps
             * @default []
             */
            steps: unknown[];
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Created
             * @default
             */
            created: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
        };
        /**
         * TextResponse
         * @description 返回纯文本内容的通用响应。
         *
         *     Generic response returning plain text content.
         */
        TextResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * ToolCallResponse
         * @description 工具调用端点响应。
         *
         *     ``/api/tools/call`` response.
         */
        ToolCallResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /** Status */
            status?: string | null;
            /** Output */
            output?: string | null;
            /** Needs Confirm */
            needs_confirm?: boolean | null;
        };
        /**
         * ToolFunction
         * @description 单个工具函数的元数据（名称 + 描述 + 参数 schema）。
         *
         *     Metadata for a single tool function (name + description + parameter schema).
         */
        ToolFunction: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            parameters: components["schemas"]["FunctionParams"];
        };
        /**
         * ToolSchema
         * @description 工具定义（含 function 字段，符合 OpenAI tools schema）。
         *
         *     Tool definition (with ``function`` field, compatible with OpenAI tools schema).
         */
        ToolSchema: {
            /**
             * Type
             * @default function
             */
            type: string;
            function: components["schemas"]["ToolFunction"];
        };
        /**
         * ToolsConfigOut
         * @description 工具配置输出。
         *
         *     Tools config output.
         */
        ToolsConfigOut: {
            /**
             * Search Max Results
             * @default 5
             */
            search_max_results: number;
            /**
             * Weather Timeout
             * @default 10
             */
            weather_timeout: number;
        };
        /**
         * ToolsResponse
         * @description 工具列表端点响应。
         *
         *     ``/api/tools`` list response.
         */
        ToolsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Tools
             * @default []
             */
            tools: components["schemas"]["ToolSchema"][];
        };
        /**
         * TtsSectionEditable
         * @description TTS 区段（多一个 enabled 标记）。
         *
         *     TTS section (extra ``enabled`` flag).
         */
        TtsSectionEditable: {
            /**
             * Active
             * @default
             */
            active: string;
            /**
             * Profiles
             * @default {}
             */
            profiles: {
                [key: string]: components["schemas"]["ProfileEditable"];
            };
            /**
             * Api Key Set
             * @default {}
             */
            api_key_set: {
                [key: string]: boolean;
            };
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /**
         * VadConfig
         * @description VAD（语音活动检测）配置。
         *
         *     ⚠️ 本类是 `core/config/schema.py` 里 VadConfig 的**手工副本**（两处定义必须同步）：
         *     FastAPI 的 response_model 会在序列化时**丢掉响应里多余字段**，故只改配置模型
         *     而不同步这里，新增字段会被静默过滤掉、前端收不到。
         *
         *     VAD (Voice Activity Detection) configuration.
         *
         *     NOTE: this is a hand-maintained **duplicate** of the VadConfig in
         *     `core/config/schema.py`; the two must be kept in sync. FastAPI's response_model drops
         *     extra fields during serialization, so adding a field only to the config model would be
         *     silently filtered out and never reach the frontend.
         */
        VadConfig: {
            /**
             * Silence Threshold
             * @default 0.02
             */
            silence_threshold: number;
            /**
             * Silence Duration Ms
             * @default 1500
             */
            silence_duration_ms: number;
            /**
             * Max Duration Ms
             * @default 10000
             */
            max_duration_ms: number;
            /**
             * Answer Timeout Ms
             * @default 8000
             */
            answer_timeout_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WakeWordConfig
         * @description 唤醒词配置。
         *
         *     Wake-word detection configuration.
         */
        WakeWordConfig: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Keyword
             * @default
             */
            keyword: string;
            /**
             * Sensitivity
             * @default 0.5
             */
            sensitivity: number;
            /**
             * Model Path
             * @default
             */
            model_path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_api_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    config_endpoint_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    patch_config_api_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchConfigResponse"];
                };
            };
        };
    };
    tts_synthesize_api_tts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    voice_transcribe_api_voice_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
        };
    };
    voice_utter_api_voice_utter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    voice_answer_api_voice_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    task_stop_api_task__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_list_api_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsResponse"];
                };
            };
        };
    };
    tools_call_api_tools_call_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallResponse"];
                };
            };
        };
    };
    env_api_env_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvResponse"];
                };
            };
        };
    };
    memory_list_api_memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListResponse"];
                };
            };
        };
    };
    memory_delete_api_memory__topic__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedules_list_api_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulesResponse"];
                };
            };
        };
    };
    schedules_add_api_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleAddResponse"];
                };
            };
        };
    };
    schedules_delete_api_schedules__sid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_list_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_get_api_history__conv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_delete_api_history__conv_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_list_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryListResponse"];
                };
            };
        };
    };
    library_detail_api_library__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_delete_api_library__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_list_api_sessions_get: {
        parameters: {
            query?: {
                archived?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_create_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
        };
    };
    sessions_delete_api_sessions__sid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_patch_api_sessions__sid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_clear_api_sessions__sid__clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_full_api_config_full_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigFullResponse"];
                };
            };
        };
    };
    put_secrets_api_config_secrets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutSecretsResponse"];
                };
            };
        };
    };
    detection_api_detection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    fetch_models_api_providers_fetch_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchModelsResponse"];
                };
            };
        };
    };
    spa_handler__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
