/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config Endpoint */
        get: operations["config_endpoint_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Config
         * @description 持久化非敏感配置并热重载；server 绑定类 / MCP 变更返回 restart_required=true。
         */
        patch: operations["patch_config_api_config_patch"];
        trace?: never;
    };
    "/api/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tts Synthesize
         * @description 文本转语音：调后端配置的 OpenAI 兼容 TTS 端点，返回音频字节。
         *
         *     请求体：{"text": "...", "voice": "可选，缺省用配置里的 voice"}
         */
        post: operations["tts_synthesize_api_tts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Transcribe */
        post: operations["voice_transcribe_api_voice_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/utter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Utter
         * @description 编排入口：文本(语音转写后/文字输入) → SSE 事件流。
         *
         *     事件：task_state / content_delta / question / error / done。
         *     question 事件后需操作者回答：POST /api/voice/answer {session_id, text}。
         */
        post: operations["voice_utter_api_voice_utter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Answer
         * @description 投递操作者对澄清/确认问题的回答，解除 pipeline 的 ask() 阻塞。
         */
        post: operations["voice_answer_api_voice_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Task Stop
         * @description 停止该会话的整个任务（CancellationToken → executor/子进程中止）。
         */
        post: operations["task_stop_api_task__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tools List
         * @description 工具清单：后端 @tool 注册中心的 OpenAI schema 数组（供控制台展示）。
         */
        get: operations["tools_list_api_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tools Call */
        post: operations["tools_call_api_tools_call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Env */
        get: operations["env_api_env_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory List */
        get: operations["memory_list_api_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Memory Delete */
        delete: operations["memory_delete_api_memory__topic__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schedules List */
        get: operations["schedules_list_api_schedules_get"];
        put?: never;
        /** Schedules Add */
        post: operations["schedules_add_api_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Schedules Delete */
        delete: operations["schedules_delete_api_schedules__sid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History List */
        get: operations["history_list_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{conv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Get */
        get: operations["history_get_api_history__conv_id__get"];
        put?: never;
        post?: never;
        /** History Delete */
        delete: operations["history_delete_api_history__conv_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Full
         * @description 设置页可编辑快照（密钥不回显）。
         */
        get: operations["config_full_api_config_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Secrets
         * @description 设置/清除密钥（value 为空字符串=清除）。path 形如 llm.api_key / llm.profiles.deepseek / server.api_token。
         *
         *     只写 config.secrets.yaml，永不把密钥值放进响应。
         */
        put: operations["put_secrets_api_config_secrets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detection
         * @description 聚合检测：环境快照 + 配置健康 + 三项连通性（设置页「检测全部」按钮）。
         */
        get: operations["detection_api_detection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/fetch-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Models
         * @description 拉取某 profile 的可用模型列表（按协议分派：openai / anthropic / gemini）。
         *
         *     请求体：{"section": "llm|asr|tts", "profile": {完整 profile dict，含 name/endpoint/chat_path/api_key_env}}
         *     profile 传完整 dict，未保存的新 profile 也能测（密钥由服务端按优先级解析，不回显）。
         */
        post: operations["fetch_models_api_providers_fetch_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa Handler */
        get: operations["spa_handler__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckResponse */
        AckResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Ack
             * @default
             */
            ack: string;
        };
        /** AgentConfigOut */
        AgentConfigOut: {
            /**
             * Recursion Limit
             * @default 12
             */
            recursion_limit: number;
            /**
             * Multi Agent
             * @default false
             */
            multi_agent: boolean;
            /**
             * Models Failover
             * @default []
             */
            models_failover: string[];
        };
        /** ApiResponse */
        ApiResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** CatalogResponse */
        CatalogResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Catalog
             * @default {}
             */
            catalog: {
                [key: string]: components["schemas"]["ProviderPreset"][];
            };
        };
        /** ConfigFullResponse */
        ConfigFullResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            editable: components["schemas"]["EditableSnapshot"];
        };
        /** ConfigHealthOut */
        ConfigHealthOut: {
            /** Ok */
            ok: boolean;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["DetectionIssue"][];
        };
        /** ConfigResponse */
        ConfigResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Llm Available
             * @default false
             */
            llm_available: boolean;
            /**
             * Llm Profile
             * @default
             */
            llm_profile: string;
            /**
             * Asr Available
             * @default false
             */
            asr_available: boolean;
            /**
             * Asr Profile
             * @default
             */
            asr_profile: string;
            /**
             * Tts Available
             * @default false
             */
            tts_available: boolean;
            /**
             * Tts Profile
             * @default
             */
            tts_profile: string;
            /** Tts Voice */
            tts_voice?: string | null;
            /** Tts Model */
            tts_model?: string | null;
            wake_word: components["schemas"]["WakeWordConfig"];
            vad: components["schemas"]["VadConfig"];
        };
        /** ConnectivityResult */
        ConnectivityResult: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** DetectionIssue */
        DetectionIssue: {
            /** Level */
            level: string;
            /** Key */
            key: string;
            /** Message */
            message: string;
        };
        /** DetectionReportOut */
        DetectionReportOut: {
            /**
             * Environment
             * @default {}
             */
            environment: {
                [key: string]: unknown;
            };
            config: components["schemas"]["ConfigHealthOut"];
            /**
             * Connectivity
             * @default []
             */
            connectivity: components["schemas"]["ConnectivityResult"][];
        };
        /** DetectionResponse */
        DetectionResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            report: components["schemas"]["DetectionReportOut"];
        };
        /** EditableSnapshot */
        EditableSnapshot: {
            llm: components["schemas"]["SectionEditable"];
            asr: components["schemas"]["SectionEditable"];
            tts: components["schemas"]["TtsSectionEditable"];
            wake_word: components["schemas"]["WakeWordConfig"];
            vad: components["schemas"]["VadConfig"];
            agent: components["schemas"]["AgentConfigOut"];
            llm_client: components["schemas"]["LlmClientConfigOut"];
            tools: components["schemas"]["ToolsConfigOut"];
            mcp: components["schemas"]["McpConfigOut"];
            rag: components["schemas"]["RagConfigOut"];
            server: components["schemas"]["ServerConfigOut"];
        };
        /** EnvResponse */
        EnvResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Content
             * @default
             */
            content: string;
        };
        /** FactItem */
        FactItem: {
            /** Topic */
            topic: string;
            /** Content */
            content: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Ts
             * @default
             */
            ts: string;
        };
        /** FetchModelsResponse */
        FetchModelsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /** FunctionParams */
        FunctionParams: {
            /**
             * Type
             * @default object
             */
            type: string;
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: unknown;
            };
            /**
             * Required
             * @default []
             */
            required: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryConversation */
        HistoryConversation: {
            /** Id */
            id: string;
            /** Created */
            created: string;
            /** Updated */
            updated: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Message Count */
            message_count: number;
        };
        /**
         * HistoryConversationDetail
         * @description 会话详情：详情响应不含 message_count（仅列表接口统计）。
         */
        HistoryConversationDetail: {
            /** Id */
            id: string;
            /** Created */
            created: string;
            /** Updated */
            updated: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["HistoryMessage"][];
        };
        /** HistoryDetailResponse */
        HistoryDetailResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            conversation?: components["schemas"]["HistoryConversationDetail"] | null;
        };
        /** HistoryListResponse */
        HistoryListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Conversations
             * @default []
             */
            conversations: components["schemas"]["HistoryConversation"][];
        };
        /** HistoryMessage */
        HistoryMessage: {
            /** Role */
            role: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** LlmClientConfigOut */
        LlmClientConfigOut: {
            /**
             * Retry Max
             * @default 3
             */
            retry_max: number;
            /**
             * Retry Backoff Base
             * @default 0.5
             */
            retry_backoff_base: number;
            /**
             * Retry Backoff Max
             * @default 10
             */
            retry_backoff_max: number;
            /**
             * Circuit Breaker Threshold
             * @default 5
             */
            circuit_breaker_threshold: number;
            /**
             * Circuit Breaker Cooldown
             * @default 30
             */
            circuit_breaker_cooldown: number;
            /**
             * Request Timeout
             * @default 60
             */
            request_timeout: number;
        };
        /** McpConfigOut */
        McpConfigOut: {
            /**
             * Servers
             * @default []
             */
            servers: components["schemas"]["McpServerOut"][];
        };
        /** McpServerOut */
        McpServerOut: {
            /** Name */
            name: string;
            /** Command */
            command: string;
            /**
             * Args
             * @default []
             */
            args: string[];
        };
        /** MemoryListResponse */
        MemoryListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["FactItem"][];
        };
        /** PatchConfigResponse */
        PatchConfigResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Restart Required
             * @default false
             */
            restart_required: boolean;
        };
        /** PingResponse */
        PingResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /** Time */
            time: string;
        };
        /**
         * ProfileEditable
         * @description editable_snapshot 的 profile（去 api_key）。extra=allow 保留用户透传键。
         */
        ProfileEditable: {
            /**
             * Provider
             * @default openai
             */
            provider: string;
            /**
             * Vendor
             * @default
             */
            vendor: string;
            /**
             * Endpoint
             * @default
             */
            endpoint: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Vision Model
             * @default
             */
            vision_model: string;
            /**
             * Chat Path
             * @default
             */
            chat_path: string;
            /**
             * Api Key Env
             * @default
             */
            api_key_env: string;
            /**
             * Timeout
             * @default 30
             */
            timeout: number;
            /**
             * Max Tokens
             * @default 4096
             */
            max_tokens: number;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Language
             * @default zh
             */
            language: string;
            /**
             * Voice
             * @default
             */
            voice: string;
            /**
             * Format
             * @default wav
             */
            format: string;
            /** Voice Ref */
            voice_ref?: string | null;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Models Path
             * @default
             */
            models_path: string;
            /**
             * Voices
             * @default []
             */
            voices: string[];
            /**
             * Compat
             * @default {}
             */
            compat: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** ProviderPreset */
        ProviderPreset: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "llm" | "asr" | "tts";
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Provider
             * @default openai
             */
            provider: string;
            /**
             * Endpoint
             * @default
             */
            endpoint: string;
            /**
             * Chat Path
             * @default
             */
            chat_path: string;
            /** Models Path */
            models_path?: string | null;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Vision Models
             * @default []
             */
            vision_models: string[];
            /**
             * Voices
             * @default []
             */
            voices: string[];
            /**
             * Api Key Env
             * @default
             */
            api_key_env: string;
            /**
             * Compat
             * @default {}
             */
            compat: {
                [key: string]: unknown;
            };
            /**
             * Defaults
             * @default {}
             */
            defaults: {
                [key: string]: unknown;
            };
        };
        /** PutSecretsResponse */
        PutSecretsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Set
             * @default false
             */
            set: boolean;
            /**
             * Path
             * @default
             */
            path: string;
        };
        /** RagConfigOut */
        RagConfigOut: {
            /**
             * Auto Index
             * @default true
             */
            auto_index: boolean;
        };
        /** ScheduleAddResponse */
        ScheduleAddResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            schedule?: components["schemas"]["ScheduleItem"] | null;
        };
        /** ScheduleItem */
        ScheduleItem: {
            /** Id */
            id: string;
            /** Cron */
            cron: string;
            /** Prompt */
            prompt: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** SchedulesResponse */
        SchedulesResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Schedules
             * @default []
             */
            schedules: components["schemas"]["ScheduleItem"][];
        };
        /** SectionEditable */
        SectionEditable: {
            /**
             * Active
             * @default
             */
            active: string;
            /**
             * Profiles
             * @default {}
             */
            profiles: {
                [key: string]: components["schemas"]["ProfileEditable"];
            };
            /**
             * Api Key Set
             * @default {}
             */
            api_key_set: {
                [key: string]: boolean;
            };
        };
        /** ServerConfigOut */
        ServerConfigOut: {
            /**
             * Host
             * @default 127.0.0.1
             */
            host: string;
            /**
             * Port
             * @default 8520
             */
            port: number;
            /**
             * Open Browser
             * @default true
             */
            open_browser: boolean;
            /**
             * Cors Origins
             * @default []
             */
            cors_origins: string[];
            /**
             * Api Token Set
             * @default false
             */
            api_token_set: boolean;
        };
        /** TextResponse */
        TextResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** ToolCallResponse */
        ToolCallResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /** Status */
            status?: string | null;
            /** Output */
            output?: string | null;
            /** Needs Confirm */
            needs_confirm?: boolean | null;
        };
        /** ToolFunction */
        ToolFunction: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            parameters: components["schemas"]["FunctionParams"];
        };
        /** ToolSchema */
        ToolSchema: {
            /**
             * Type
             * @default function
             */
            type: string;
            function: components["schemas"]["ToolFunction"];
        };
        /** ToolsConfigOut */
        ToolsConfigOut: {
            /**
             * Search Max Results
             * @default 5
             */
            search_max_results: number;
            /**
             * Weather Timeout
             * @default 10
             */
            weather_timeout: number;
        };
        /** ToolsResponse */
        ToolsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Tools
             * @default []
             */
            tools: components["schemas"]["ToolSchema"][];
        };
        /** TtsSectionEditable */
        TtsSectionEditable: {
            /**
             * Active
             * @default
             */
            active: string;
            /**
             * Profiles
             * @default {}
             */
            profiles: {
                [key: string]: components["schemas"]["ProfileEditable"];
            };
            /**
             * Api Key Set
             * @default {}
             */
            api_key_set: {
                [key: string]: boolean;
            };
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /** VadConfig */
        VadConfig: {
            /**
             * Silence Threshold
             * @default 0.02
             */
            silence_threshold: number;
            /**
             * Silence Duration Ms
             * @default 1500
             */
            silence_duration_ms: number;
            /**
             * Max Duration Ms
             * @default 10000
             */
            max_duration_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WakeWordConfig */
        WakeWordConfig: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Keyword
             * @default
             */
            keyword: string;
            /**
             * Sensitivity
             * @default 0.5
             */
            sensitivity: number;
            /**
             * Model Path
             * @default
             */
            model_path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_api_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    config_endpoint_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    patch_config_api_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchConfigResponse"];
                };
            };
        };
    };
    tts_synthesize_api_tts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    voice_transcribe_api_voice_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
        };
    };
    voice_utter_api_voice_utter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    voice_answer_api_voice_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    task_stop_api_task__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_list_api_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsResponse"];
                };
            };
        };
    };
    tools_call_api_tools_call_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallResponse"];
                };
            };
        };
    };
    env_api_env_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvResponse"];
                };
            };
        };
    };
    memory_list_api_memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListResponse"];
                };
            };
        };
    };
    memory_delete_api_memory__topic__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedules_list_api_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulesResponse"];
                };
            };
        };
    };
    schedules_add_api_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleAddResponse"];
                };
            };
        };
    };
    schedules_delete_api_schedules__sid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_list_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_get_api_history__conv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_delete_api_history__conv_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_full_api_config_full_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigFullResponse"];
                };
            };
        };
    };
    put_secrets_api_config_secrets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutSecretsResponse"];
                };
            };
        };
    };
    detection_api_detection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    fetch_models_api_providers_fetch_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchModelsResponse"];
                };
            };
        };
    };
    spa_handler__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
